# Generated by Django 5.0.7 on 2024-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use pen name, and not real name', max_length=70, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AlterField(
            model_name='books',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favourite?'),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='books', to='books.authors'),
        ),
    ]
